apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: saml-application
  annotations:
    github.com/project-slug: jbatu-deloitte/saml-application
spec:
  type: service
  lifecycle: experimental
  owner: user:default/jbatu-deloitte
  providesApis:
    - authentication-api
